In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/Downloads/archive/quikr_car.csv")

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        892 non-null    str
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 41.9 KB

#### 1)price str
#### 2)kms driven null
#### 3)fuel_type null and maybe missing
#### 4)duplicates
#### 5)outliers

In [5]:
df.shape

(892, 6)

In [6]:
df["kms_driven"].unique

<bound method Series.unique of 0      45,000 kms
1          40 kms
2      22,000 kms
3      28,000 kms
4      36,000 kms
          ...
887           NaN
888    27,000 kms
889    40,000 kms
890        Petrol
891        Petrol
Name: kms_driven, Length: 892, dtype: str>

In [7]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [8]:
df["kms_driven"]=df["kms_driven"].str.replace("kms","")

In [9]:
df["kms_driven"]=df["kms_driven"].str.replace(",","")

In [10]:
df["kms_driven"]

0      45000
1         40
2      22000
3      28000
4      36000
        ...
887       NaN
888    27000
889    40000
890    Petrol
891    Petrol
Name: kms_driven, Length: 892, dtype: str

In [11]:
df=df[df["Price"] != "Ask For Price"]

In [12]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000",45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000",28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000",36000,Diesel
6,Ford Figo,Ford,2012,"1,75,000",41000,Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000",27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000",40000,Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [13]:
df=df[df["kms_driven"] != "Petrol"]

In [14]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000",45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000",28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000",36000,Diesel
6,Ford Figo,Ford,2012,"1,75,000",41000,Diesel
...,...,...,...,...,...,...
885,Tata Indica V2 DLE BS III,Tata,2009,"1,10,000",30000,Diesel
886,Toyota Corolla Altis,Toyota,2009,"3,00,000",132000,Petrol
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000",27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000",40000,Diesel

In [15]:
df.isna().sum()

name           0
company        0
year           0
Price          0
kms_driven    38
fuel_type     39
dtype: int64

In [16]:
df.describe

<bound method NDFrame.describe of                                        name   company  year     Price  \
0      Hyundai Santro Xing XO eRLX Euro III   Hyundai  2007    80,000
1                   Mahindra Jeep CL550 MDI  Mahindra  2006  4,25,000
3    Hyundai Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014  3,25,000
4          Ford EcoSport Titanium 1.5L TDCi      Ford  2014  5,75,000
6                                 Ford Figo      Ford  2012  1,75,000
..                                      ...       ...   ...       ...
885               Tata Indica V2 DLE BS III      Tata  2009  1,10,000
886                    Toyota Corolla Altis    Toyota  2009  3,00,000
887                                      Ta      Tara  zest  3,10,000
888                     Tata Zest XM Diesel      Tata  2018  2,60,000
889                      Mahindra Quanto C8  Mahindra  2013  3,90,000

    kms_driven fuel_type
0       45000     Petrol
1          40     Diesel
3       28000     Petrol
4       36000     Diesel
6       41000     Diesel
..         ...       ...
885     30000     Diesel
886    132000     Petrol
887        NaN       NaN
888     27000     Diesel
889     40000     Diesel

[855 rows x 6 columns]>

In [17]:
df=df.dropna(subset=["fuel_type"])

In [18]:
df.info()

<class 'pandas.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    str
 1   company     816 non-null    str
 2   year        816 non-null    str
 3   Price       816 non-null    str
 4   kms_driven  816 non-null    str
 5   fuel_type   816 non-null    str
dtypes: str(6)
memory usage: 44.6 KB

In [19]:
df.isna().sum()

name          0
company       0
year          0
Price         0
kms_driven    0
fuel_type     0
dtype: int64

In [20]:
df["Price"]

0        80,000
1      4,25,000
3      3,25,000
4      5,75,000
6      1,75,000
         ...
883    2,70,000
885    1,10,000
886    3,00,000
888    2,60,000
889    3,90,000
Name: Price, Length: 816, dtype: str

In [21]:
df["Price"]=df["Price"].str.replace(",",'')

In [22]:
df["Price"]

0       80000
1      425000
3      325000
4      575000
6      175000
        ...
883    270000
885    110000
886    300000
888    260000
889    390000
Name: Price, Length: 816, dtype: str

In [23]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
888,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [24]:
df.reset_index(drop=True)

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
2,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
3,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
4,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...
811,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
812,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
813,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
814,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
815,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [25]:
df.head(n=30)

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,Ford Figo,Ford,2012,175000,41000,Diesel
7,Hyundai Eon,Hyundai,2013,190000,25000,Petrol
8,Ford EcoSport Ambiente 1.5L TDCi,Ford,2016,830000,24530,Diesel
9,Maruti Suzuki Alto K10 VXi AMT,Maruti,2015,250000,60000,Petrol
10,Skoda Fabia Classic 1.2 MPI,Skoda,2010,182000,60000,Petrol
11,Maruti Suzuki Stingray VXi,Maruti,2015,315000,30000,Petrol
12,Hyundai Elite i20 Magna 1.2,Hyundai,2014,415000,32000,Petrol
13,Mahindra Scorpio SLE BS IV,Mahindra,2015,320000,48660,Diesel
14,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
15,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
16,Audi A8,Audi,2017,1000000,4000,Petrol
17,Audi Q7,Audi,2014,500000,16934,Diesel
18,Mahindra Scorpio S10,Mahindra,2016,350000,43000,Diesel
19,Maruti Suzuki Alto 800,Maruti,2014,160000,35550,Petrol
20,Mahindra Scorpio S10,Mahindra,2016,350000,43000,Diesel
21,Mahindra Scorpio S10,Mahindra,2016,310000,39522,Diesel
22,Maruti Suzuki Alto 800 Vxi,Maruti,2015,75000,39000,Petrol
23,Hyundai i20 Sportz 1.2,Hyundai,2012,100000,55000,Petrol
24,Hyundai i20 Sportz 1.2,Hyundai,2012,100000,55000,Petrol
25,Hyundai i20 Sportz 1.2,Hyundai,2012,100000,55000,Petrol
26,Maruti Suzuki Alto 800 Lx,Maruti,2017,190000,72000,Petrol
27,Maruti Suzuki Vitara Brezza ZDi,Maruti,2016,290000,15975,Diesel
28,Maruti Suzuki Alto LX,Maruti,2008,95000,70000,Petrol
29,Mahindra Bolero DI,Mahindra,2017,180000,23452,Diesel
30,Maruti Suzuki Swift Dzire ZDi,Maruti,2014,385000,35522,Diesel
31,Mahindra Scorpio S10 4WD,Mahindra,2015,250000,48508,Diesel

In [26]:
df["Price"].isna().sum()

np.int64(0)

In [27]:
df.info()

<class 'pandas.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    str
 1   company     816 non-null    str
 2   year        816 non-null    str
 3   Price       816 non-null    str
 4   kms_driven  816 non-null    str
 5   fuel_type   816 non-null    str
dtypes: str(6)
memory usage: 44.6 KB

In [28]:
df["Price"]=df["Price"].astype(int)

In [29]:
df.info()

<class 'pandas.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    str
 1   company     816 non-null    str
 2   year        816 non-null    str
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    str
 5   fuel_type   816 non-null    str
dtypes: int64(1), str(5)
memory usage: 44.6 KB

In [30]:
df["kms_driven"]=df["kms_driven"].astype(int)

In [31]:
df["year"]=df["year"].astype(int)

In [32]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
888,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [33]:
# df.sort_values("name")
# df[df["name"].duplicated(keep=False)]

In [34]:
df["name"]

0        Hyundai Santro Xing XO eRLX Euro III
1                     Mahindra Jeep CL550 MDI
3      Hyundai Grand i10 Magna 1.2 Kappa VTVT
4            Ford EcoSport Titanium 1.5L TDCi
6                                   Ford Figo
                        ...
883                Maruti Suzuki Ritz VXI ABS
885                 Tata Indica V2 DLE BS III
886                      Toyota Corolla Altis
888                       Tata Zest XM Diesel
889                        Mahindra Quanto C8
Name: name, Length: 816, dtype: str

In [35]:
df["name"]

0        Hyundai Santro Xing XO eRLX Euro III
1                     Mahindra Jeep CL550 MDI
3      Hyundai Grand i10 Magna 1.2 Kappa VTVT
4            Ford EcoSport Titanium 1.5L TDCi
6                                   Ford Figo
                        ...
883                Maruti Suzuki Ritz VXI ABS
885                 Tata Indica V2 DLE BS III
886                      Toyota Corolla Altis
888                       Tata Zest XM Diesel
889                        Mahindra Quanto C8
Name: name, Length: 816, dtype: str

In [36]:
df.sort_values("name")

,name,company,year,Price,kms_driven,fuel_type
719,Audi A3 Cabriolet 40 TFSI,Audi,2015,3100000,12516,Petrol
245,Audi A4 1.8 TFSI Multitronic Premium Plus,Audi,2009,699000,47000,Petrol
230,Audi A4 1.8 TFSI Multitronic Premium Plus,Audi,2009,699000,47000,Petrol
338,Audi A4 2.0 TDI 177bhp Premium,Audi,2012,1350000,40000,Diesel
678,Audi A4 2.0 TDI 177bhp Premium,Audi,2016,1900000,44000,Diesel
...,...,...,...,...,...,...
86,Volkswagen Vento Highline Plus 1.5 Diesel AT,Volkswagen,2019,1200000,3600,Diesel
439,Volkswagen Vento Highline Plus 1.5 Diesel AT,Volkswagen,2015,550000,34000,Diesel
407,Volkswagen Vento Konekt Diesel Highline,Volkswagen,2011,245000,65000,Diesel
398,Volkswagen Vento Konekt Diesel Highline,Volkswagen,2011,245000,65000,Diesel
692,Volvo S80 Summum D4,Volvo,2015,1850000,42000,Diesel

In [37]:
df=df.drop_duplicates(keep="first")
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
888,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [38]:
df.reset_index(drop=True)

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
2,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
3,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
4,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...
719,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
720,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
721,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
722,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
723,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [39]:
df.info()

<class 'pandas.DataFrame'>
Index: 724 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        724 non-null    str
 1   company     724 non-null    str
 2   year        724 non-null    int64
 3   Price       724 non-null    int64
 4   kms_driven  724 non-null    int64
 5   fuel_type   724 non-null    str
dtypes: int64(3), str(3)
memory usage: 39.6 KB

In [40]:
df.describe()

              year         Price     kms_driven
count   724.000000  7.240000e+02     724.000000
mean   2012.321823  4.032451e+05   46791.342541
std       4.122940  4.802936e+05   34575.416435
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.650000e+05   27000.000000
50%    2013.000000  2.900000e+05   42000.000000
75%    2015.000000  4.899990e+05   59000.000000
max    2019.000000  8.500003e+06  400000.000000

In [41]:
df[df["Price"]>2000000]

,name,company,year,Price,kms_driven,fuel_type
232,Land Rover Freelander 2 SE,Land,2015,2100000,30000,Diesel
510,Jaguar XE XE Portfolio,Jaguar,2016,2800000,8500,Petrol
562,Mahindra XUV500 W6,Mahindra,2014,8500003,45000,Diesel
667,Jaguar XF 2.2 Diesel Luxury,Jaguar,2013,2190000,29000,Diesel
668,Audi Q5 2.0 TDI quattro Premium Plus,Audi,2014,2390000,34000,Diesel
719,Audi A3 Cabriolet 40 TFSI,Audi,2015,3100000,12516,Petrol
838,Ford Endeavor 4x4 Thunder Plus,Ford,2019,2900000,9000,Diesel

In [42]:
df=df[df["Price"]!= 8500003]
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
888,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [43]:
df.reset_index(drop=True,inplace=True)

In [44]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
2,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
3,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
4,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...
718,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
719,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
720,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
721,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
722,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [45]:
df.describe()

              year         Price     kms_driven
count   723.000000  7.230000e+02     723.000000
mean   2012.319502  3.920462e+05   46793.820194
std       4.125321  3.742673e+05   34599.288028
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.650000e+05   27000.000000
50%    2013.000000  2.900000e+05   42000.000000
75%    2015.000000  4.899990e+05   59000.000000
max    2019.000000  3.100000e+06  400000.000000

In [46]:
df["fuel_type"].value_counts()

fuel_type
Petrol    390
Diesel    331
LPG         2
Name: count, dtype: int64

In [47]:
df["company"].value_counts()

company
Maruti        202
Hyundai       129
Mahindra       77
Tata           61
Honda          51
Toyota         34
Chevrolet      33
Ford           26
Renault        26
Volkswagen     17
Skoda          10
Audi           10
BMW             8
Datsun          6
Nissan          6
Mercedes        6
Mitsubishi      5
Mini            3
Hindustan       3
Fiat            3
Force           2
Jaguar          2
Land            1
Jeep            1
Volvo           1
Name: count, dtype: int64

In [48]:
df.to_csv("cleaned_car.csv")

In [49]:
x=df.drop(columns="Price")
y=df["Price"]

In [50]:
x,y

(                                       name   company  year  kms_driven  \
 0      Hyundai Santro Xing XO eRLX Euro III   Hyundai  2007       45000
 1                   Mahindra Jeep CL550 MDI  Mahindra  2006          40
 2    Hyundai Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014       28000
 3          Ford EcoSport Titanium 1.5L TDCi      Ford  2014       36000
 4                                 Ford Figo      Ford  2012       41000
 ..                                      ...       ...   ...         ...
 718              Maruti Suzuki Ritz VXI ABS    Maruti  2011       50000
 719               Tata Indica V2 DLE BS III      Tata  2009       30000
 720                    Toyota Corolla Altis    Toyota  2009      132000
 721                     Tata Zest XM Diesel      Tata  2018       27000
 722                      Mahindra Quanto C8  Mahindra  2013       40000

     fuel_type
 0      Petrol
 1      Diesel
 2      Petrol
 3      Diesel
 4      Diesel
 ..        ...
 718    Petrol
 719    Diesel
 720    Petrol
 721    Diesel
 722    Diesel

 [723 rows x 5 columns],
 0       80000
 1      425000
 2      325000
 3      575000
 4      175000
         ...
 718    270000
 719    110000
 720    300000
 721    260000
 722    390000
 Name: Price, Length: 723, dtype: int64)

In [51]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [52]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder

In [53]:
model=LinearRegression()

In [54]:
model.fit(X_train, y_train)

NameError: name 'X_train' is not defined

In [63]:
(df["company"]=="BMW").sum()

np.int64(8)

In [72]:
df[df["company"]=="Maruti"]

,name,company,year,Price,kms_driven,fuel_type
7,Maruti Suzuki Alto K10 VXi AMT,Maruti,2015,250000,60000,Petrol
9,Maruti Suzuki Stingray VXi,Maruti,2015,315000,30000,Petrol
15,Maruti Suzuki Alto 800,Maruti,2014,160000,35550,Petrol
17,Maruti Suzuki Alto 800 Vxi,Maruti,2015,75000,39000,Petrol
19,Maruti Suzuki Alto 800 Lx,Maruti,2017,190000,72000,Petrol
...,...,...,...,...,...,...
706,Maruti Suzuki Swift Dzire,Maruti,2016,350000,146000,Diesel
710,Maruti Suzuki Dzire,Maruti,2016,325000,150000,Diesel
713,Maruti Suzuki Dzire,Maruti,2016,450000,2500,Diesel
716,Maruti Suzuki Alto LXi BS III,Maruti,2005,95000,65000,Petrol
718,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol